### ISSUE TITLE
Is it possible to make this project by latest crossbridge??

### ISSUE THREAD

**Issue by foodyi** [lua-alchemy/lua-alchemy#8]
may be performance better?

**Comment by agladysh** [comment]
The performance should be better. But it will take some work. I don't use Lua-Alchemy anymore --- moved to JS-based solution (e.g. https://github.com/logiceditor-com/lua5.1.js/). But if you'd like to sponsor the port, please contact me in private (see my profile on GitHub for an e-mail).
